# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jim's Technical Blog
email: jim.buzz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My technical blog where I record my various electronic and computing stuff. This is mainly to allow me to record my technical successes and otherwise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://parkyjimbo.github.io" # the base hostname & protocol for your site
twitter_username: parkyjimbo
github_username:  parkyjimbo

# Build settings
markdown: kramdown
